config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :doctors
  devise_for :clients
  
  resources :doctors

  resources :clients do
    resources :animals
  end

  resources :cities
  resources :appointments

  get 'team',     to: 'static_page#team'
  get 'contact',  to: 'static_page#contact'
  get 'cgu',      to: 'static_page#cgu'
  
  root to: "welcome#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
    belongs_to :city
    belongs_to :client
    has_many :doctors, through: :appointments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :city
    belongs_to :doctor
    belongs_to :client
    belongs_to :animal
end

app/models/city.rb
class City < ApplicationRecord
    has_many :doctors
    has_many :clients
    has_many :animals
    has_many :appointments

end

app/models/client.rb
class Client < User
    after_create :welcome_send

    belongs_to :city
    has_many :doctors
    has_many :animals
    has_many :appointments

    

  def welcome_send
    ClientMailer.welcome_email(self).deliver_now
  end
end

app/models/doctor.rb
class Doctor < User
    after_create :welcome_send
    
    belongs_to :city
    has_many :appointments
    has_many :clients
    has_many :animals, through: :appointments
    has_many :specialities

  def welcome_send
    DoctorMailer.welcome_email(self).deliver_now
  end

end

app/models/specialty.rb
class Specialty < ApplicationRecord
    belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # le <self.abstract_class = true> empêche la page "mot de passe oublié" de s'afficher
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    def index

    end
  
    def show
  
    end
  
    def new
  
    end
  
    def create
      
    end
  
    def edit
  
    end
  
    def update
  
    end
  
    def destroy
      
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  
  def index

  end

  def show

  end

  def new
 
  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
   
  end

  def show
    
  end

  def new
    
  end

  def create
   
  end

  def edit
   
  end

  def update
    
  end

  def destroy 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #before_action :authentificate_user!

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="welcome_bg-image">
  <nav class="navbar navbar-expand-lg">
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Recherche</button>
      </form>
  </nav>
</div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
    <div class="container d-flex justify-content-center">
      <div class="row">

        <div class="text-white col-md-6"> 
          
          <img class="welcome-card-img" data-src="" alt="Card image"
            src="https://resize.prod.femina.ladmedia.fr/rblr/652,438/img/var/2020-10/animaux-enfant-deuil-mort-perte.jpg">

            <p>JE TROUVE MON VÉTÉRINAIRE</p>
            <p>Prenez rendez-vous en ligne avec votre vétérinaire 24h/24 et 7j/7.</p>
            <p>Simple, sécurisé et entièrement gratuit.</p>
          
              <button class="btn-light btn-sm btn-outline-secondary"><%= link_to "Inscription ", new_client_registration_path %></button>
              <button class="btn-light btn-sm btn-outline-secondary"> <%= link_to "Connexion", client_session_path %></button>
        </div>

        <div class="text-white col-md-6">

          <img class="welcome-card-img" data-src="" alt="Card image" 
            src="https://i.f1g.fr/media/eidos/805x453_crop/2021/09/14/XVMb4df1bce-14a7-11ec-86f5-55eefe3d3177.jpg">
         
            <p>VOUS ÊTES VÉTÉRINAIRE ?</p>
            <p>Découvrez notre plateforme innovante sans abonnement ni engagement.</p>
            <p>Conçu pour la profession vétérinaire.</p>
        
              <button class="btn-light btn-sm btn-outline-secondary"> <%= link_to "Inscription", new_doctor_registration_path %></button>
              <button class="btn-light btn-sm btn-outline-secondary"> <%= link_to "Connexion", doctor_session_path %></button>
        </div>
      </div>
    </div>
  </nav>