config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :doctors
  devise_for :clients
  
  resources :doctors

  resources :clients do
    resources :animals
  end

  resources :cities
  resources :appointments

  get 'team',     to: 'static_page#team'
  get 'contact',  to: 'static_page#contact'
  get 'cgu',      to: 'static_page#cgu'
  
  root to: "welcome#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
    belongs_to :city
    belongs_to :client
    has_many :doctors, through: :appointments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :city
    belongs_to :doctor
    belongs_to :client
    belongs_to :animal
end

app/models/city.rb
class City < ApplicationRecord
    has_many :doctors
    has_many :clients
    has_many :animals
    has_many :appointments

end

app/models/client.rb
class Client < User
    after_create :welcome_send

    belongs_to :city
    has_many :doctors
    has_many :animals
    has_many :appointments

    

  def welcome_send
    ClientMailer.welcome_email(self).deliver_now
  end
end

app/models/doctor.rb
class Doctor < User
    after_create :welcome_send
    
    belongs_to :city
    has_many :appointments
    has_many :clients
    has_many :animals, through: :appointments
    has_many :specialities

  def welcome_send
    DoctorMailer.welcome_email(self).deliver_now
  end

end

app/models/specialty.rb
class Specialty < ApplicationRecord
    belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # le <self.abstract_class = true> empêche la page "mot de passe oublié" de s'afficher
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  
  def index

  end

  def show

  end

  def new
 
  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
   
  end

  def show
    
  end

  def new
    
  end

  def create
   
  end

  def edit
   
  end

  def update
    
  end

  def destroy 
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
  <!-- ========== FOOTER ========== -->
  <footer>
  
    <p class="text-muted text-center small p-1 mb-6">Pour nous suivre !</p>
    <div class="social text-center">
      <a class="mx-3 h4 d-inline-block text-primary" href="https://twitter.com">Twitter</a>
      <a class="mx-3 h4 d-inline-block text-secondary" href="https://www.facebook.com">Facebook</a>
      <a class="mx-3 h4 d-inline-block text-warning" href="https://www.instagram.com">Instagram</a>
    
      <!-- Copyright -->
      <div class="text-center p-2">
        Tous droits réservés © Fait par Kimia ALARY, Camille BAE, Christel COVI, Taos TOUAHRIA
        <br>THP HIVER 2022<br>
        <%= link_to "CGU", cgu_path %>
      </div>
    </div>
  </footer>
  <!-- ========== END FOOTER ========== -->

app/views/layouts/_header.html.erb
<!-- ========== HEADER ========== -->
<head>
 <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <div class="logo">
        <div class="col-md-6 card mb-6 box-shadow">
          <img src="https://media.istockphoto.com/vectors/veterinary-clinic-vector-logo-vector-id1148571478?s=170x170"
            class="card-img-top" alt="...">
          ANIMALIB
        </div>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item btn-outline-secondary">
           <%= link_to "Accueil", root_path,  class: "nav-link" %>
          </li>
          <li class="nav-item btn-outline-secondary">
           <%= link_to "Team", team_path,  class: "nav-link" %>
          </li>

          <li class="nav-item btn-outline-secondary">
           <%= link_to "Contact", contact_path,  class: "nav-link" %>
          </li>

          <li class="nav-item dropdown btn-outline-secondary">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">S'identifier</a>
            <div class="dropdown-menu">
             <%= link_to "Vétérinaire", doctor_session_path,  class: "dropdown-item"%>
             <%= link_to "Client", client_session_path,  class: "dropdown-item"%>
             <%= link_to "Inscription", new_client_registration_path,  class: "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>
<!-- ========== END HEADER ========== -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Animalib</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

   <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

   <%= render 'layouts/footer' %>
  </body>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</html>